# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_ui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(929, 776)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.mSettingBox = QtWidgets.QGroupBox(self.centralwidget)
        self.mSettingBox.setGeometry(QtCore.QRect(210, 20, 701, 91))
        self.mSettingBox.setObjectName("mSettingBox")
        self.str_gateTime = QtWidgets.QLabel(self.mSettingBox)
        self.str_gateTime.setGeometry(QtCore.QRect(10, 20, 81, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.str_gateTime.setFont(font)
        self.str_gateTime.setObjectName("str_gateTime")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.mSettingBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 151, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.getTime_hLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.getTime_hLayout.setContentsMargins(0, 0, 0, 0)
        self.getTime_hLayout.setObjectName("getTime_hLayout")
        self.gate_time = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.gate_time.setObjectName("gate_time")
        self.getTime_hLayout.addWidget(self.gate_time)
        self.x50ns = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.x50ns.setObjectName("x50ns")
        self.getTime_hLayout.addWidget(self.x50ns)
        self.str_readData = QtWidgets.QLabel(self.mSettingBox)
        self.str_readData.setGeometry(QtCore.QRect(180, 20, 141, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.str_readData.setFont(font)
        self.str_readData.setObjectName("str_readData")
        self.str_mesTime = QtWidgets.QLabel(self.mSettingBox)
        self.str_mesTime.setGeometry(QtCore.QRect(340, 20, 121, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.str_mesTime.setFont(font)
        self.str_mesTime.setObjectName("str_mesTime")
        self.btn_measure = QtWidgets.QPushButton(self.mSettingBox)
        self.btn_measure.setGeometry(QtCore.QRect(490, 40, 75, 23))
        self.btn_measure.setObjectName("btn_measure")
        self.btn_loopStop = QtWidgets.QPushButton(self.mSettingBox)
        self.btn_loopStop.setGeometry(QtCore.QRect(600, 60, 81, 23))
        self.btn_loopStop.setObjectName("btn_loopStop")
        self.m_time = QtWidgets.QLineEdit(self.mSettingBox)
        self.m_time.setGeometry(QtCore.QRect(340, 40, 101, 20))
        self.m_time.setObjectName("m_time")
        self.str_gateTime_2 = QtWidgets.QLabel(self.mSettingBox)
        self.str_gateTime_2.setGeometry(QtCore.QRect(450, 40, 51, 16))
        self.str_gateTime_2.setObjectName("str_gateTime_2")
        self.read_data = QtWidgets.QLineEdit(self.mSettingBox)
        self.read_data.setGeometry(QtCore.QRect(180, 40, 121, 20))
        self.read_data.setObjectName("read_data")
        self.btn_loopStart = QtWidgets.QPushButton(self.mSettingBox)
        self.btn_loopStart.setGeometry(QtCore.QRect(600, 20, 81, 23))
        self.btn_loopStart.setObjectName("btn_loopStart")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(20, 10, 171, 101))
        self.logo.setObjectName("logo")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 120, 511, 301))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.countCh1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.countCh1.setContentsMargins(0, 0, 0, 0)
        self.countCh1.setObjectName("countCh1")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(530, 120, 391, 301))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.sumCh1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.sumCh1.setContentsMargins(0, 0, 0, 0)
        self.sumCh1.setObjectName("sumCh1")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 430, 511, 301))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.countCh2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.countCh2.setContentsMargins(0, 0, 0, 0)
        self.countCh2.setObjectName("countCh2")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(530, 430, 391, 301))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.sumCh2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.sumCh2.setContentsMargins(0, 0, 0, 0)
        self.sumCh2.setObjectName("sumCh2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 929, 21))
        self.menubar.setObjectName("menubar")
        self.menu_Quit = QtWidgets.QMenu(self.menubar)
        self.menu_Quit.setObjectName("menu_Quit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Quit = QtWidgets.QAction(MainWindow)
        self.action_Quit.setObjectName("action_Quit")
        self.action_Save = QtWidgets.QAction(MainWindow)
        self.action_Save.setObjectName("action_Save")
        self.menu_Quit.addAction(self.action_Save)
        self.menu_Quit.addAction(self.action_Quit)
        self.menubar.addAction(self.menu_Quit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.mSettingBox.setTitle(_translate("MainWindow", "Measurement Setting"))
        self.str_gateTime.setText(_translate("MainWindow", "Gate Time"))
        self.gate_time.setText(_translate("MainWindow", "50"))
        self.x50ns.setText(_translate("MainWindow", "* 50nsec"))
        self.str_readData.setText(_translate("MainWindow", "Read Data (MAX: 64M)"))
        self.str_mesTime.setText(_translate("MainWindow", "Measurement Time"))
        self.btn_measure.setText(_translate("MainWindow", "Measure"))
        self.btn_loopStop.setText(_translate("MainWindow", "Loop_Stop"))
        self.m_time.setText(_translate("MainWindow", "2.5"))
        self.str_gateTime_2.setText(_translate("MainWindow", "sec."))
        self.read_data.setText(_translate("MainWindow", "1000000"))
        self.btn_loopStart.setText(_translate("MainWindow", "Loop_Start"))
        self.logo.setText(_translate("MainWindow", "TextLabel"))
        self.menu_Quit.setTitle(_translate("MainWindow", "File"))
        self.action_Quit.setText(_translate("MainWindow", "&Quit"))
        self.action_Quit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.action_Save.setText(_translate("MainWindow", "&Save"))
        self.action_Save.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))

