# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_ui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(929, 629)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.ySetttingBox = QtWidgets.QGroupBox(self.centralwidget)
        self.ySetttingBox.setGeometry(QtCore.QRect(10, 140, 199, 151))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.ySetttingBox.setFont(font)
        self.ySetttingBox.setObjectName("ySetttingBox")
        self.PhotonCounting = QtWidgets.QLabel(self.ySetttingBox)
        self.PhotonCounting.setGeometry(QtCore.QRect(10, 40, 101, 16))
        self.PhotonCounting.setObjectName("PhotonCounting")
        self.Upper = QtWidgets.QLabel(self.ySetttingBox)
        self.Upper.setGeometry(QtCore.QRect(40, 20, 31, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Upper.setFont(font)
        self.Upper.setObjectName("Upper")
        self.Lower = QtWidgets.QLabel(self.ySetttingBox)
        self.Lower.setGeometry(QtCore.QRect(120, 20, 31, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Lower.setFont(font)
        self.Lower.setObjectName("Lower")
        self.summation = QtWidgets.QLabel(self.ySetttingBox)
        self.summation.setGeometry(QtCore.QRect(10, 90, 101, 16))
        self.summation.setObjectName("summation")
        self.pCh1_y = QtWidgets.QLineEdit(self.ySetttingBox)
        self.pCh1_y.setGeometry(QtCore.QRect(10, 60, 81, 21))
        self.pCh1_y.setObjectName("pCh1_y")
        self.pCh2_y = QtWidgets.QLineEdit(self.ySetttingBox)
        self.pCh2_y.setGeometry(QtCore.QRect(100, 60, 81, 21))
        self.pCh2_y.setObjectName("pCh2_y")
        self.sumCh1_y = QtWidgets.QLineEdit(self.ySetttingBox)
        self.sumCh1_y.setGeometry(QtCore.QRect(10, 110, 81, 21))
        self.sumCh1_y.setObjectName("sumCh1_y")
        self.sumCh2_y = QtWidgets.QLineEdit(self.ySetttingBox)
        self.sumCh2_y.setGeometry(QtCore.QRect(100, 110, 81, 21))
        self.sumCh2_y.setObjectName("sumCh2_y")
        self.mSettingBox = QtWidgets.QGroupBox(self.centralwidget)
        self.mSettingBox.setGeometry(QtCore.QRect(10, 310, 199, 271))
        self.mSettingBox.setObjectName("mSettingBox")
        self.str_gateTime = QtWidgets.QLabel(self.mSettingBox)
        self.str_gateTime.setGeometry(QtCore.QRect(10, 20, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.str_gateTime.setFont(font)
        self.str_gateTime.setObjectName("str_gateTime")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.mSettingBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 40, 151, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.getTime_hLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.getTime_hLayout.setContentsMargins(0, 0, 0, 0)
        self.getTime_hLayout.setObjectName("getTime_hLayout")
        self.gate_time = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.gate_time.setObjectName("gate_time")
        self.getTime_hLayout.addWidget(self.gate_time)
        self.x50ns = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.x50ns.setObjectName("x50ns")
        self.getTime_hLayout.addWidget(self.x50ns)
        self.str_readData = QtWidgets.QLabel(self.mSettingBox)
        self.str_readData.setGeometry(QtCore.QRect(10, 90, 141, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.str_readData.setFont(font)
        self.str_readData.setObjectName("str_readData")
        self.str_mesTime = QtWidgets.QLabel(self.mSettingBox)
        self.str_mesTime.setGeometry(QtCore.QRect(10, 140, 121, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.str_mesTime.setFont(font)
        self.str_mesTime.setObjectName("str_mesTime")
        self.loop_start = QtWidgets.QPushButton(self.mSettingBox)
        self.loop_start.setGeometry(QtCore.QRect(10, 210, 75, 23))
        self.loop_start.setObjectName("loop_start")
        self.dataSave = QtWidgets.QPushButton(self.mSettingBox)
        self.dataSave.setGeometry(QtCore.QRect(60, 240, 75, 23))
        self.dataSave.setObjectName("dataSave")
        self.loot_stop = QtWidgets.QPushButton(self.mSettingBox)
        self.loot_stop.setGeometry(QtCore.QRect(110, 210, 75, 23))
        self.loot_stop.setObjectName("loot_stop")
        self.m_time = QtWidgets.QLineEdit(self.mSettingBox)
        self.m_time.setGeometry(QtCore.QRect(10, 160, 121, 20))
        self.m_time.setObjectName("m_time")
        self.str_gateTime_2 = QtWidgets.QLabel(self.mSettingBox)
        self.str_gateTime_2.setGeometry(QtCore.QRect(140, 160, 51, 16))
        self.str_gateTime_2.setObjectName("str_gateTime_2")
        self.read_data = QtWidgets.QLineEdit(self.mSettingBox)
        self.read_data.setGeometry(QtCore.QRect(10, 110, 151, 20))
        self.read_data.setObjectName("read_data")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(50, 20, 101, 101))
        self.logo.setObjectName("logo")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(220, 10, 441, 281))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.countCh1 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.countCh1.setContentsMargins(0, 0, 0, 0)
        self.countCh1.setObjectName("countCh1")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(670, 10, 251, 281))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.sumCh1 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.sumCh1.setContentsMargins(0, 0, 0, 0)
        self.sumCh1.setObjectName("sumCh1")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(220, 300, 441, 281))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.countCh2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.countCh2.setContentsMargins(0, 0, 0, 0)
        self.countCh2.setObjectName("countCh2")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(670, 300, 251, 281))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.sumCh2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.sumCh2.setContentsMargins(0, 0, 0, 0)
        self.sumCh2.setObjectName("sumCh2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 929, 21))
        self.menubar.setObjectName("menubar")
        self.menu_Quit = QtWidgets.QMenu(self.menubar)
        self.menu_Quit.setObjectName("menu_Quit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Quit = QtWidgets.QAction(MainWindow)
        self.action_Quit.setObjectName("action_Quit")
        self.menu_Quit.addAction(self.action_Quit)
        self.menubar.addAction(self.menu_Quit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ySetttingBox.setTitle(_translate("MainWindow", "Y-axis Setting"))
        self.PhotonCounting.setText(_translate("MainWindow", "Photon Counting"))
        self.Upper.setText(_translate("MainWindow", "Ch1"))
        self.Lower.setText(_translate("MainWindow", "Ch2"))
        self.summation.setText(_translate("MainWindow", "Sumation"))
        self.pCh1_y.setText(_translate("MainWindow", "10"))
        self.pCh2_y.setText(_translate("MainWindow", "10"))
        self.sumCh1_y.setText(_translate("MainWindow", "2000"))
        self.sumCh2_y.setText(_translate("MainWindow", "2000"))
        self.mSettingBox.setTitle(_translate("MainWindow", "Measurement Setting"))
        self.str_gateTime.setText(_translate("MainWindow", "Gate Time"))
        self.gate_time.setText(_translate("MainWindow", "50"))
        self.x50ns.setText(_translate("MainWindow", "* 50nsec"))
        self.str_readData.setText(_translate("MainWindow", "Read Data (MAX: 64M)"))
        self.str_mesTime.setText(_translate("MainWindow", "Measurement Time"))
        self.loop_start.setText(_translate("MainWindow", "Start"))
        self.dataSave.setText(_translate("MainWindow", "Save"))
        self.loot_stop.setText(_translate("MainWindow", "Stop"))
        self.m_time.setText(_translate("MainWindow", "2.5"))
        self.str_gateTime_2.setText(_translate("MainWindow", "sec."))
        self.read_data.setText(_translate("MainWindow", "1000000"))
        self.logo.setText(_translate("MainWindow", "TextLabel"))
        self.menu_Quit.setTitle(_translate("MainWindow", "&Quit"))
        self.action_Quit.setText(_translate("MainWindow", "&Quit"))
        self.action_Quit.setShortcut(_translate("MainWindow", "Ctrl+Q"))

