# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_ui_tab.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(950, 750)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.mSettingBox = QtWidgets.QGroupBox(self.centralwidget)
        self.mSettingBox.setGeometry(QtCore.QRect(110, 10, 691, 91))
        self.mSettingBox.setObjectName("mSettingBox")
        self.str_gateTime = QtWidgets.QLabel(self.mSettingBox)
        self.str_gateTime.setGeometry(QtCore.QRect(160, 30, 81, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.str_gateTime.setFont(font)
        self.str_gateTime.setObjectName("str_gateTime")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.mSettingBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(160, 40, 151, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.getTime_hLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.getTime_hLayout.setContentsMargins(0, 0, 0, 0)
        self.getTime_hLayout.setObjectName("getTime_hLayout")
        self.gate_time = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.gate_time.setObjectName("gate_time")
        self.getTime_hLayout.addWidget(self.gate_time)
        self.x50ns = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.x50ns.setObjectName("x50ns")
        self.getTime_hLayout.addWidget(self.x50ns)
        self.str_readData = QtWidgets.QLabel(self.mSettingBox)
        self.str_readData.setGeometry(QtCore.QRect(360, 30, 141, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.str_readData.setFont(font)
        self.str_readData.setObjectName("str_readData")
        self.str_mesTime = QtWidgets.QLabel(self.mSettingBox)
        self.str_mesTime.setGeometry(QtCore.QRect(540, 30, 121, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.str_mesTime.setFont(font)
        self.str_mesTime.setObjectName("str_mesTime")
        self.m_time = QtWidgets.QLineEdit(self.mSettingBox)
        self.m_time.setGeometry(QtCore.QRect(540, 50, 101, 20))
        self.m_time.setObjectName("m_time")
        self.str_gateTime_2 = QtWidgets.QLabel(self.mSettingBox)
        self.str_gateTime_2.setGeometry(QtCore.QRect(650, 50, 51, 16))
        self.str_gateTime_2.setObjectName("str_gateTime_2")
        self.read_data = QtWidgets.QLineEdit(self.mSettingBox)
        self.read_data.setGeometry(QtCore.QRect(360, 50, 121, 20))
        self.read_data.setObjectName("read_data")
        self.channelBox = QtWidgets.QComboBox(self.mSettingBox)
        self.channelBox.setGeometry(QtCore.QRect(10, 40, 121, 32))
        self.channelBox.setObjectName("channelBox")
        self.channelBox.addItem("")
        self.channelBox.addItem("")
        self.channelBox.addItem("")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(20, 10, 61, 101))
        self.logo.setObjectName("logo")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 110, 911, 581))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_fcs = QtWidgets.QWidget()
        self.tab_fcs.setObjectName("tab_fcs")
        self.countingdetails = QtWidgets.QGroupBox(self.tab_fcs)
        self.countingdetails.setGeometry(QtCore.QRect(500, 340, 391, 131))
        self.countingdetails.setObjectName("countingdetails")
        self.str_mesTime_3 = QtWidgets.QLabel(self.countingdetails)
        self.str_mesTime_3.setGeometry(QtCore.QRect(610, 30, 121, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.str_mesTime_3.setFont(font)
        self.str_mesTime_3.setObjectName("str_mesTime_3")
        self.m_time_3 = QtWidgets.QLineEdit(self.countingdetails)
        self.m_time_3.setGeometry(QtCore.QRect(610, 50, 101, 20))
        self.m_time_3.setObjectName("m_time_3")
        self.str_gateTime_5 = QtWidgets.QLabel(self.countingdetails)
        self.str_gateTime_5.setGeometry(QtCore.QRect(720, 50, 51, 16))
        self.str_gateTime_5.setObjectName("str_gateTime_5")
        self.calc_total_photon = QtWidgets.QLineEdit(self.countingdetails)
        self.calc_total_photon.setGeometry(QtCore.QRect(250, 30, 113, 21))
        self.calc_total_photon.setObjectName("calc_total_photon")
        self.calc_cpm = QtWidgets.QLineEdit(self.countingdetails)
        self.calc_cpm.setGeometry(QtCore.QRect(250, 80, 113, 21))
        self.calc_cpm.setObjectName("calc_cpm")
        self.logo_2 = QtWidgets.QLabel(self.countingdetails)
        self.logo_2.setGeometry(QtCore.QRect(30, 30, 171, 21))
        self.logo_2.setObjectName("logo_2")
        self.logo_3 = QtWidgets.QLabel(self.countingdetails)
        self.logo_3.setGeometry(QtCore.QRect(30, 80, 171, 21))
        self.logo_3.setObjectName("logo_3")
        self.FCS_PC_widget = QtWidgets.QWidget(self.tab_fcs)
        self.FCS_PC_widget.setGeometry(QtCore.QRect(10, 0, 481, 271))
        self.FCS_PC_widget.setObjectName("FCS_PC_widget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.FCS_PC_widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 481, 271))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.FCS_PC_Layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.FCS_PC_Layout.setContentsMargins(0, 0, 0, 0)
        self.FCS_PC_Layout.setObjectName("FCS_PC_Layout")
        self.FCS_CF_widget = QtWidgets.QWidget(self.tab_fcs)
        self.FCS_CF_widget.setGeometry(QtCore.QRect(495, 0, 401, 271))
        self.FCS_CF_widget.setObjectName("FCS_CF_widget")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.FCS_CF_widget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 401, 271))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.FCS_CF_Layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.FCS_CF_Layout.setContentsMargins(0, 0, 0, 0)
        self.FCS_CF_Layout.setObjectName("FCS_CF_Layout")
        self.FCS_PS_widget = QtWidgets.QWidget(self.tab_fcs)
        self.FCS_PS_widget.setGeometry(QtCore.QRect(10, 273, 481, 271))
        self.FCS_PS_widget.setObjectName("FCS_PS_widget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.FCS_PS_widget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 481, 271))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.FCS_PS_Layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.FCS_PS_Layout.setContentsMargins(0, 0, 0, 0)
        self.FCS_PS_Layout.setObjectName("FCS_PS_Layout")
        self.tabWidget.addTab(self.tab_fcs, "")
        self.tab_fccs = QtWidgets.QWidget()
        self.tab_fccs.setObjectName("tab_fccs")
        self.Ch1_PC_widget = QtWidgets.QWidget(self.tab_fccs)
        self.Ch1_PC_widget.setGeometry(QtCore.QRect(10, 0, 481, 271))
        self.Ch1_PC_widget.setObjectName("Ch1_PC_widget")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.Ch1_PC_widget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 481, 271))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.FCCS_Ch1_photonCount = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.FCCS_Ch1_photonCount.setContentsMargins(0, 0, 0, 0)
        self.FCCS_Ch1_photonCount.setObjectName("FCCS_Ch1_photonCount")
        self.Ch2_PC_widget = QtWidgets.QWidget(self.tab_fccs)
        self.Ch2_PC_widget.setGeometry(QtCore.QRect(10, 273, 481, 271))
        self.Ch2_PC_widget.setObjectName("Ch2_PC_widget")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.Ch2_PC_widget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(0, 0, 481, 271))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.FCCS_Ch2_photonCount = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.FCCS_Ch2_photonCount.setContentsMargins(0, 0, 0, 0)
        self.FCCS_Ch2_photonCount.setObjectName("FCCS_Ch2_photonCount")
        self.widget = QtWidgets.QWidget(self.tab_fccs)
        self.widget.setGeometry(QtCore.QRect(495, 0, 401, 271))
        self.widget.setObjectName("widget")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.widget)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(0, 0, 401, 271))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.FCCS_Ch1_colFunc = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.FCCS_Ch1_colFunc.setContentsMargins(0, 0, 0, 0)
        self.FCCS_Ch1_colFunc.setObjectName("FCCS_Ch1_colFunc")
        self.widget_2 = QtWidgets.QWidget(self.tab_fccs)
        self.widget_2.setGeometry(QtCore.QRect(495, 273, 401, 281))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.widget_2)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(0, 0, 401, 271))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.FCCS_Ch2_colFunc = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.FCCS_Ch2_colFunc.setContentsMargins(0, 0, 0, 0)
        self.FCCS_Ch2_colFunc.setObjectName("FCCS_Ch2_colFunc")
        self.tabWidget.addTab(self.tab_fccs, "")
        self.saveFigBtn = QtWidgets.QPushButton(self.centralwidget)
        self.saveFigBtn.setGeometry(QtCore.QRect(550, 695, 111, 32))
        self.saveFigBtn.setObjectName("saveFigBtn")
        self.measureBtn = QtWidgets.QPushButton(self.centralwidget)
        self.measureBtn.setGeometry(QtCore.QRect(304, 695, 111, 31))
        self.measureBtn.setObjectName("measureBtn")
        self.saveDataBtn = QtWidgets.QPushButton(self.centralwidget)
        self.saveDataBtn.setGeometry(QtCore.QRect(430, 695, 111, 32))
        self.saveDataBtn.setObjectName("saveDataBtn")
        self.spot_search = QtWidgets.QGroupBox(self.centralwidget)
        self.spot_search.setGeometry(QtCore.QRect(800, 10, 131, 91))
        self.spot_search.setObjectName("spot_search")
        self.str_mesTime_2 = QtWidgets.QLabel(self.spot_search)
        self.str_mesTime_2.setGeometry(QtCore.QRect(610, 30, 121, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.str_mesTime_2.setFont(font)
        self.str_mesTime_2.setObjectName("str_mesTime_2")
        self.m_time_2 = QtWidgets.QLineEdit(self.spot_search)
        self.m_time_2.setGeometry(QtCore.QRect(610, 50, 101, 20))
        self.m_time_2.setObjectName("m_time_2")
        self.str_gateTime_4 = QtWidgets.QLabel(self.spot_search)
        self.str_gateTime_4.setGeometry(QtCore.QRect(720, 50, 51, 16))
        self.str_gateTime_4.setObjectName("str_gateTime_4")
        self.btn_loopStop = QtWidgets.QPushButton(self.spot_search)
        self.btn_loopStop.setGeometry(QtCore.QRect(10, 50, 101, 31))
        self.btn_loopStop.setObjectName("btn_loopStop")
        self.btn_loopStart = QtWidgets.QPushButton(self.spot_search)
        self.btn_loopStart.setGeometry(QtCore.QRect(10, 20, 101, 31))
        self.btn_loopStart.setObjectName("btn_loopStart")
        self.tabWidget.raise_()
        self.mSettingBox.raise_()
        self.logo.raise_()
        self.saveFigBtn.raise_()
        self.measureBtn.raise_()
        self.saveDataBtn.raise_()
        self.spot_search.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Quit = QtWidgets.QAction(MainWindow)
        self.action_Quit.setObjectName("action_Quit")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.mSettingBox.setTitle(_translate("MainWindow", "Measurement Setting"))
        self.str_gateTime.setText(_translate("MainWindow", "Gate Time"))
        self.gate_time.setText(_translate("MainWindow", "2"))
        self.x50ns.setText(_translate("MainWindow", "* 50nsec"))
        self.str_readData.setText(_translate("MainWindow", "Read Data (MAX: 64M)"))
        self.str_mesTime.setText(_translate("MainWindow", "Measurement Time"))
        self.m_time.setText(_translate("MainWindow", "2.5"))
        self.str_gateTime_2.setText(_translate("MainWindow", "sec."))
        self.read_data.setText(_translate("MainWindow", "1000000"))
        self.channelBox.setItemText(0, _translate("MainWindow", "Ch. 1 (Green)"))
        self.channelBox.setItemText(1, _translate("MainWindow", "Ch. 2 (Red)"))
        self.channelBox.setItemText(2, _translate("MainWindow", "Ch. 1, Ch, 2"))
        self.logo.setText(_translate("MainWindow", "TextLabel"))
        self.countingdetails.setTitle(_translate("MainWindow", "Counting Details"))
        self.str_mesTime_3.setText(_translate("MainWindow", "Measurement Time"))
        self.m_time_3.setText(_translate("MainWindow", "2.5"))
        self.str_gateTime_5.setText(_translate("MainWindow", "sec."))
        self.logo_2.setText(_translate("MainWindow", "Total number of Photons :"))
        self.logo_3.setText(_translate("MainWindow", "Count / molecules :"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_fcs), _translate("MainWindow", "FCS"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_fccs), _translate("MainWindow", "FCCS"))
        self.saveFigBtn.setText(_translate("MainWindow", "Save as EPS"))
        self.measureBtn.setText(_translate("MainWindow", "Measure"))
        self.saveDataBtn.setText(_translate("MainWindow", "Save as CSV"))
        self.spot_search.setTitle(_translate("MainWindow", "Confocal spot search"))
        self.str_mesTime_2.setText(_translate("MainWindow", "Measurement Time"))
        self.m_time_2.setText(_translate("MainWindow", "2.5"))
        self.str_gateTime_4.setText(_translate("MainWindow", "sec."))
        self.btn_loopStop.setText(_translate("MainWindow", "Loop_Stop"))
        self.btn_loopStart.setText(_translate("MainWindow", "Loop_Start"))
        self.action_Quit.setText(_translate("MainWindow", "&Quit"))
        self.action_Quit.setShortcut(_translate("MainWindow", "Ctrl+Q"))

